# SPDX-License-Identifier: Apache-2.0

"""Frozen public constants for the Rayline ARC encoder contract."""

MODEL_ID = "Qwen/Qwen3.5-0.8B"
MODEL_REVISION = "2fc06364715b967f1860aea9cf38778875588b17"
TOKENIZER_REVISION = MODEL_REVISION
TOKENIZER_SHA256 = "5f9e4d4901a92b997e463c1f46055088b6cca5ca61a6522d1b9f64c4bb81cb42"

EOS_TOKEN = "<|im_end|>"
EOS_TOKEN_ID = 248046
EMBEDDING_DIMENSION = 1024
TOKEN_EMBEDDING_RANK = 2
# Matches torch.nn.functional.normalize's default epsilon, which the Rung B
# in-engine head uses; means below this norm are degenerate on both rungs.
NORMALIZATION_EPSILON = 1e-12
MAX_SERIALIZED_TOKENS = 262_144
MIN_SERIALIZED_TOKENS = 16
MIN_RECENT_TURNS = 1
MIN_RECENT_TOKENS = 64
MAX_REQUEST_BYTES = 16 * 1024 * 1024
MAX_TURNS = 4096

SERIALIZER_VERSION = "mtrouter-token-blocks-v2"
REQUEST_SCHEMA_VERSION = "rayline.arc.pooling-request.v1"
SESSION_REQUEST_SCHEMA_VERSION = "rayline.arc.session-pooling-request.v1"
SESSION_RESPONSE_SCHEMA_VERSION = "rayline.arc.session-pooling-response.v1"
PLUGIN_VERSION = "rayline-arc-io@0.1.0"
RUNG_A_CAPABILITIES = ("all_plugin_mean",)
RUNG_B_CAPABILITIES = ("chunked_causal_mean",)
SESSION_CAPABILITIES = ("chunked_causal_mean", "resumable_causal_mean")

# This probe covers Unicode and proves that literal special-token text is
# parsed as ordinary content. It is generated by the pinned tokenizer and the
# authoritative Rayline llama.cpp serializer.
TOKENIZER_PROBE_TEXT = "[Task]\ncafé 😀 <|im_end|>"
TOKENIZER_PROBE_IDS = (
    58,
    6065,
    60,
    198,
    895,
    56868,
    87209,
    79790,
    316,
    6018,
    91,
    29,
)
